name: Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Stats (light)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: stats
          options: username=jsuarezruiz&show_icons=true&hide_border=true&count_private=true&include_all_commits=true&show=reviews,prs_merged,prs_merged_percentage,discussions_started
          path: site/stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          fail_on_error: true

      - name: Stats (dark)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: stats
          options: username=jsuarezruiz&show_icons=true&hide_border=true&count_private=true&include_all_commits=true&show=reviews,prs_merged,prs_merged_percentage,discussions_started&theme=github_dark
          path: site/stats-dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          fail_on_error: true

      - name: Top languages (light)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=jsuarezruiz&hide_border=true&layout=donut&langs_count=8&hide=javascript
          path: site/top-langs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          fail_on_error: true

      - name: Top languages (dark)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=jsuarezruiz&hide_border=true&layout=donut&langs_count=8&hide=javascript&theme=github_dark
          path: site/top-langs-dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          fail_on_error: true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4
